---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-model
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smart-model
    spec:
      containers:
      - name: smart-model
        image: kohestanimahdi/smart-model:1.0
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: smart-model
---
apiVersion: v1
kind: Service
metadata:
  name: smart-model
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: smart-model