---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-feature
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smart-feature
    spec:
      containers:
      - name: smart-feature
        image: kohestanimahdi/smart-feature:1.6
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: smart-model-url
          value: http://smart-model
  selector:
    matchLabels:
      app: smart-feature
---
apiVersion: v1
kind: Service
metadata:
  name: smart-feature
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: smart-feature